# app/services/pdf_service.py

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Preformatted
)


# =====================================================
# SAFE VALUE HELPERS
# =====================================================

def safe_text(value, default="Not available."):

    if value is None:
        return default

    if isinstance(value, str):

        value = value.strip()

        if not value:
            return default

        return value

    if isinstance(value, list):

        if not value:
            return default

        return ", ".join(
            str(item)
            for item in value
        )

    if isinstance(value, dict):

        if not value:
            return default

        return " | ".join(
            f"{key}: {val}"
            for key, val in value.items()
        )

    return str(value)


def safe_list(value):

    if value is None:
        return []

    if isinstance(value, list):
        return value

    if isinstance(value, tuple):
        return list(value)

    if isinstance(value, str):

        if not value.strip():
            return []

        return [value]

    return [value]


def escape_html(text):

    text = safe_text(
        text,
        ""
    )

    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


# =====================================================
# PAGE HEADER / FOOTER + DARK BORDER
# =====================================================

def add_page_number(canvas, doc):

    canvas.saveState()

    width, height = A4

    # -------------------------------------------------
    # DARK BORDER AROUND EVERY PAGE
    # -------------------------------------------------

    canvas.setStrokeColor(
        colors.HexColor("#0F172A")
    )

    canvas.setLineWidth(1.5)

    canvas.rect(
        8 * mm,
        8 * mm,
        width - 16 * mm,
        height - 16 * mm
    )

    # -------------------------------------------------
    # HEADER
    # -------------------------------------------------

    canvas.setFont(
        "Helvetica-Bold",
        8
    )

    canvas.setFillColor(
        colors.HexColor("#6366F1")
    )

    canvas.drawString(
        18 * mm,
        height - 12 * mm,
        "GITORA AI"
    )

    canvas.setFont(
        "Helvetica",
        8
    )

    canvas.setFillColor(
        colors.HexColor("#64748B")
    )

    canvas.drawRightString(
        width - 18 * mm,
        height - 12 * mm,
        "GitHub Repository Analysis"
    )

    # -------------------------------------------------
    # FOOTER LINE
    # -------------------------------------------------

    canvas.setStrokeColor(
        colors.HexColor("#CBD5E1")
    )

    canvas.setLineWidth(0.5)

    canvas.line(
        18 * mm,
        13 * mm,
        width - 18 * mm,
        13 * mm
    )

    # -------------------------------------------------
    # FOOTER TEXT
    # -------------------------------------------------

    canvas.setFont(
        "Helvetica",
        8
    )

    canvas.setFillColor(
        colors.HexColor("#64748B")
    )

    canvas.drawString(
        18 * mm,
        8 * mm,
        "Generated by Gitora AI"
    )

    canvas.drawRightString(
        width - 18 * mm,
        8 * mm,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# =====================================================
# SECTION TITLE
# =====================================================

def section_title(text, styles):

    return Paragraph(
        escape_html(text),
        styles["SectionTitle"]
    )


# =====================================================
# BULLET LIST
# =====================================================

def bullet_list(items, styles):

    elements = []

    items = safe_list(items)

    if not items:

        elements.append(
            Paragraph(
                "None identified.",
                styles["BodyTextCustom"]
            )
        )

        return elements

    for item in items:

        if isinstance(item, dict):

            text = " | ".join(
                f"{key}: {value}"
                for key, value in item.items()
            )

        else:

            text = str(item)

        elements.append(
            Paragraph(
                "• " + escape_html(text),
                styles["BulletCustom"]
            )
        )

    return elements


# =====================================================
# ANALYSIS BOX
# =====================================================

def create_analysis_box(
    title,
    content,
    styles
):

    data = [[
        Paragraph(
            escape_html(title),
            styles["BoxTitle"]
        )
    ], [
        Paragraph(
            escape_html(
                safe_text(content)
            ),
            styles["BodyTextCustom"]
        )
    ]]

    table = Table(
        data,
        colWidths=[170 * mm]
    )

    table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#EEF2FF")
            ),

            (
                "BACKGROUND",
                (0, 1),
                (-1, -1),
                colors.HexColor("#F8FAFC")
            ),

            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.8,
                colors.HexColor("#CBD5E1")
            ),

            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.3,
                colors.HexColor("#E2E8F0")
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                8
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                8
            )

        ])
    )

    return table


# =====================================================
# FILE ANALYSIS
# =====================================================

def build_file_analysis(
    file_analysis,
    styles
):

    elements = []

    if not isinstance(
        file_analysis,
        list
    ):

        return elements

    for item in file_analysis:

        if not isinstance(
            item,
            dict
        ):

            continue

        file_name = (
            item.get("file")
            or item.get("path")
            or item.get("filename")
            or "Unknown file"
        )

        elements.append(
            Paragraph(
                escape_html(file_name),
                styles["FileTitle"]
            )
        )

        what_it_does = (
            item.get("what_it_does")
            or item.get("description")
            or item.get("purpose")
        )

        why_exists = (
            item.get("why_it_exists")
            or item.get("why")
        )

        website_role = (
            item.get("website_role")
            or item.get("role")
            or item.get("how_it_helps")
        )

        dependencies = item.get(
            "dependencies"
        )

        requests = (
            item.get("important_requests")
            or item.get("api_requests")
        )

        what_breaks = (
            item.get("what_breaks")
            or item.get("impact")
        )

        elements.append(
            create_analysis_box(
                "What It Does",
                what_it_does,
                styles
            )
        )

        elements.append(
            Spacer(1, 5)
        )

        elements.append(
            create_analysis_box(
                "Why It Exists",
                why_exists,
                styles
            )
        )

        elements.append(
            Spacer(1, 5)
        )

        elements.append(
            create_analysis_box(
                "How It Helps The Website",
                website_role,
                styles
            )
        )

        elements.append(
            Spacer(1, 5)
        )

        elements.append(
            create_analysis_box(
                "Dependencies",
                safe_text(
                    dependencies,
                    "None identified."
                ),
                styles
            )
        )

        elements.append(
            Spacer(1, 5)
        )

        elements.append(
            create_analysis_box(
                "Important API Requests",
                safe_text(
                    requests,
                    "None identified."
                ),
                styles
            )
        )

        elements.append(
            Spacer(1, 5)
        )

        elements.append(
            create_analysis_box(
                "What Breaks Without This File?",
                what_breaks,
                styles
            )
        )

        elements.append(
            Spacer(1, 12)
        )

    return elements


# =====================================================
# API REQUEST TABLE
# =====================================================

def build_api_requests(
    requests,
    styles
):

    elements = []

    requests = safe_list(requests)

    if not requests:

        elements.append(
            Paragraph(
                "No important external API requests were identified.",
                styles["BodyTextCustom"]
            )
        )

        return elements

    rows = [[

        Paragraph(
            "API / Service",
            styles["TableHeader"]
        ),

        Paragraph(
            "File",
            styles["TableHeader"]
        ),

        Paragraph(
            "Purpose",
            styles["TableHeader"]
        ),

        Paragraph(
            "Usage",
            styles["TableHeader"]
        )

    ]]

    for item in requests:

        if isinstance(item, dict):

            api = (
                item.get("api")
                or item.get("service")
                or "External API"
            )

            file_name = (
                item.get("file")
                or "Not specified"
            )

            purpose = (
                item.get("purpose")
                or item.get("why")
                or "Not specified"
            )

            usage = (
                item.get("usage")
                or "Not specified"
            )

        else:

            api = "External API"
            file_name = "Not specified"
            purpose = str(item)
            usage = "Not specified"

        rows.append([

            Paragraph(
                escape_html(api),
                styles["TableCell"]
            ),

            Paragraph(
                escape_html(file_name),
                styles["TableCell"]
            ),

            Paragraph(
                escape_html(purpose),
                styles["TableCell"]
            ),

            Paragraph(
                escape_html(usage),
                styles["TableCell"]
            )

        ])

    table = Table(
        rows,
        colWidths=[
            38 * mm,
            32 * mm,
            50 * mm,
            50 * mm
        ],
        repeatRows=1
    )

    table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#6366F1")
            ),

            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.white
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.HexColor("#CBD5E1")
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP"
            ),

            (
                "BACKGROUND",
                (0, 1),
                (-1, -1),
                colors.HexColor("#F8FAFC")
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                6
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                6
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7
            )

        ])
    )

    elements.append(table)

    return elements


# =====================================================
# REBUILD OPTIONS
# =====================================================

def build_rebuild_options(
    options,
    styles
):

    elements = []

    options = safe_list(options)

    if not options:

        elements.append(
            Paragraph(
                "No rebuild approaches were generated.",
                styles["BodyTextCustom"]
            )
        )

        return elements

    for index, option in enumerate(
        options[:3],
        start=1
    ):

        if isinstance(option, dict):

            title = (
                option.get("title")
                or option.get("name")
                or option.get("approach")
                or f"Approach {index}"
            )

            description = (
                option.get("description")
                or option.get("details")
                or option.get("method")
                or option.get("technology")
                or ""
            )

            content = (
                str(title)
                + "\n\n"
                + str(description)
            )

        else:

            content = str(option)

        elements.append(
            create_analysis_box(
                f"Approach {index}",
                content,
                styles
            )
        )

        elements.append(
            Spacer(1, 8)
        )

    return elements


# =====================================================
# SOURCE CODE SECTION
# =====================================================

def build_source_code(
    source_files,
    styles
):

    elements = []

    if not source_files:

        elements.append(
            Paragraph(
                "No source files were selected.",
                styles["BodyTextCustom"]
            )
        )

        return elements

    for index, file in enumerate(
        source_files,
        start=1
    ):

        if not isinstance(
            file,
            dict
        ):

            continue

        path = safe_text(
            file.get("path"),
            f"Selected File {index}"
        )

        content = file.get(
            "content",
            ""
        )

        if content is None:
            content = ""

        content = str(content)

        categories = file.get(
            "categories",
            []
        )

        category_text = safe_text(
            categories,
            "Uncategorized"
        )

        # -------------------------------------------------
        # FILE HEADING
        # -------------------------------------------------

        elements.append(
            Paragraph(
                f"{index}. {escape_html(path)}",
                styles["CodeFileTitle"]
            )
        )

        # -------------------------------------------------
        # FILE INFORMATION
        # -------------------------------------------------

        info_data = [[

            Paragraph(
                "<b>File</b>",
                styles["BodyTextCustom"]
            ),

            Paragraph(
                escape_html(path),
                styles["BodyTextCustom"]
            ),

            Paragraph(
                "<b>Category</b>",
                styles["BodyTextCustom"]
            ),

            Paragraph(
                escape_html(category_text),
                styles["BodyTextCustom"]
            )

        ]]

        info_table = Table(
            info_data,
            colWidths=[
                18 * mm,
                62 * mm,
                25 * mm,
                65 * mm
            ]
        )

        info_table.setStyle(
            TableStyle([

                (
                    "BACKGROUND",
                    (0, 0),
                    (0, 0),
                    colors.HexColor("#E0E7FF")
                ),

                (
                    "BACKGROUND",
                    (2, 0),
                    (2, 0),
                    colors.HexColor("#E0E7FF")
                ),

                (
                    "BACKGROUND",
                    (1, 0),
                    (1, 0),
                    colors.HexColor("#F8FAFC")
                ),

                (
                    "BACKGROUND",
                    (3, 0),
                    (3, 0),
                    colors.HexColor("#F8FAFC")
                ),

                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#CBD5E1")
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE"
                ),

                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                ),

                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    5
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    5
                )

            ])
        )

        elements.append(
            info_table
        )

        elements.append(
            Spacer(1, 8)
        )

        # -------------------------------------------------
        # CODE HEADING
        # -------------------------------------------------

        elements.append(
            Paragraph(
                "Source Code",
                styles["CodeHeading"]
            )
        )

        # -------------------------------------------------
        # CODE BLOCK
        # -------------------------------------------------

        if content.strip():

            code = Preformatted(
                content,
                styles["CodeBlock"]
            )

            code_table = Table(
                [[code]],
                colWidths=[
                    170 * mm
                ]
            )

            code_table.setStyle(
                TableStyle([

                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, -1),
                        colors.HexColor("#0F172A")
                    ),

                    (
                        "BOX",
                        (0, 0),
                        (-1, -1),
                        1,
                        colors.HexColor("#1E293B")
                    ),

                    (
                        "LEFTPADDING",
                        (0, 0),
                        (-1, -1),
                        10
                    ),

                    (
                        "RIGHTPADDING",
                        (0, 0),
                        (-1, -1),
                        10
                    ),

                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        10
                    ),

                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        10
                    )

                ])
            )

            elements.append(
                code_table
            )

        else:

            elements.append(
                create_analysis_box(
                    "Source Code",
                    "Source code was not available for this file.",
                    styles
                )
            )

        elements.append(
            Spacer(1, 15)
        )

        # -------------------------------------------------
        # NEXT FILE ON NEW PAGE
        # -------------------------------------------------

        if index < len(source_files):

            elements.append(
                PageBreak()
            )

    return elements


# =====================================================
# MAIN PDF GENERATOR
# =====================================================

def generate_repository_pdf(
    repository,
    source_files,
    ai_analysis
):

    print(
        "PDF SERVICE: Starting PDF generation..."
    )

    if not isinstance(
        repository,
        dict
    ):
        repository = {}

    if not isinstance(
        source_files,
        list
    ):
        source_files = []

    if not isinstance(
        ai_analysis,
        dict
    ):
        ai_analysis = {}

    # =================================================
    # PDF BUFFER
    # =================================================

    buffer = BytesIO()

    # =================================================
    # DOCUMENT
    # =================================================

    document = SimpleDocTemplate(

        buffer,

        pagesize=A4,

        rightMargin=18 * mm,

        leftMargin=18 * mm,

        topMargin=20 * mm,

        bottomMargin=18 * mm,

        title=(
            repository.get(
                "name",
                "Gitora Repository"
            )
            + " - Gitora AI Report"
        ),

        author="Gitora AI"

    )

    # =================================================
    # STYLES
    # =================================================

    base_styles = getSampleStyleSheet()

    styles = {}

    styles["CoverTitle"] = ParagraphStyle(

        "CoverTitle",

        parent=base_styles["Title"],

        fontName="Helvetica-Bold",

        fontSize=26,

        leading=32,

        alignment=TA_CENTER,

        textColor=colors.HexColor("#312E81"),

        spaceAfter=12

    )

    styles["CoverSubtitle"] = ParagraphStyle(

        "CoverSubtitle",

        parent=base_styles["Normal"],

        fontName="Helvetica",

        fontSize=12,

        leading=18,

        alignment=TA_CENTER,

        textColor=colors.HexColor("#64748B"),

        spaceAfter=8

    )

    styles["SectionTitle"] = ParagraphStyle(

        "SectionTitle",

        parent=base_styles["Heading1"],

        fontName="Helvetica-Bold",

        fontSize=18,

        leading=23,

        textColor=colors.HexColor("#312E81"),

        spaceBefore=8,

        spaceAfter=12

    )

    styles["BodyTextCustom"] = ParagraphStyle(

        "BodyTextCustom",

        parent=base_styles["BodyText"],

        fontName="Helvetica",

        fontSize=9.5,

        leading=15,

        textColor=colors.HexColor("#334155"),

        spaceAfter=5

    )

    styles["BulletCustom"] = ParagraphStyle(

        "BulletCustom",

        parent=styles["BodyTextCustom"],

        leftIndent=12,

        firstLineIndent=-7,

        spaceAfter=4

    )

    styles["BoxTitle"] = ParagraphStyle(

        "BoxTitle",

        parent=base_styles["Heading3"],

        fontName="Helvetica-Bold",

        fontSize=10,

        leading=13,

        textColor=colors.HexColor("#4338CA"),

        spaceAfter=2

    )

    styles["FileTitle"] = ParagraphStyle(

        "FileTitle",

        parent=base_styles["Heading2"],

        fontName="Helvetica-Bold",

        fontSize=14,

        leading=18,

        textColor=colors.HexColor("#0F172A"),

        spaceBefore=10,

        spaceAfter=10

    )

    styles["TableHeader"] = ParagraphStyle(

        "TableHeader",

        parent=base_styles["Normal"],

        fontName="Helvetica-Bold",

        fontSize=8,

        leading=10,

        textColor=colors.white

    )

    styles["TableCell"] = ParagraphStyle(

        "TableCell",

        parent=base_styles["Normal"],

        fontName="Helvetica",

        fontSize=7.5,

        leading=10,

        textColor=colors.HexColor("#334155")

    )

    # =================================================
    # CODE STYLES
    # =================================================

    styles["CodeFileTitle"] = ParagraphStyle(

        "CodeFileTitle",

        parent=base_styles["Heading2"],

        fontName="Helvetica-Bold",

        fontSize=16,

        leading=21,

        textColor=colors.HexColor("#312E81"),

        spaceBefore=5,

        spaceAfter=8

    )

    styles["CodeHeading"] = ParagraphStyle(

        "CodeHeading",

        parent=base_styles["Heading3"],

        fontName="Helvetica-Bold",

        fontSize=11,

        leading=14,

        textColor=colors.HexColor("#4338CA"),

        spaceBefore=5,

        spaceAfter=6

    )

    styles["CodeBlock"] = ParagraphStyle(

        "CodeBlock",

        fontName="Courier",

        fontSize=6.8,

        leading=9,

        textColor=colors.HexColor("#E2E8F0"),

        leftIndent=0,

        rightIndent=0,

        spaceBefore=0,

        spaceAfter=0

    )

    # =================================================
    # DATA
    # =================================================

    repository_name = safe_text(
        repository.get("name"),
        "GitHub Repository"
    )

    full_name = safe_text(
        repository.get("full_name"),
        repository_name
    )

    default_branch = safe_text(
        repository.get("default_branch"),
        "Unknown"
    )

    project_summary = (
        ai_analysis.get("project_summary")
        or ai_analysis.get("summary")
        or "AI analysis was not available."
    )

    architecture = (
        ai_analysis.get("architecture")
        or "Not available."
    )

    database = (
        ai_analysis.get("database")
        or "Not available."
    )

    authentication = (
        ai_analysis.get("authentication")
        or "Not available."
    )

    technology_stack = (
        ai_analysis.get("technology_stack")
        or ai_analysis.get("technologies")
        or []
    )

    dependencies = (
        ai_analysis.get("dependencies")
        or []
    )

    important_requests = (
        ai_analysis.get("important_requests")
        or ai_analysis.get("api_requests")
        or []
    )

    file_analysis = (
        ai_analysis.get("file_analysis")
        or []
    )

    rebuild_options = (
        ai_analysis.get("rebuild_options")
        or ai_analysis.get("rebuild_ways")
        or []
    )

    # =================================================
    # BUILD DOCUMENT
    # =================================================

    story = []

    # =================================================
    # COVER
    # =================================================

    story.append(
        Spacer(
            1,
            35 * mm
        )
    )

    story.append(
        Paragraph(
            "GITORA AI",
            styles["CoverTitle"]
        )
    )

    story.append(
        Paragraph(
            "GitHub Repository Analysis Report",
            styles["CoverSubtitle"]
        )
    )

    story.append(
        Spacer(
            1,
            15 * mm
        )
    )

    cover_data = [

        [
            Paragraph(
                "<b>Repository</b>",
                styles["BodyTextCustom"]
            ),

            Paragraph(
                escape_html(repository_name),
                styles["BodyTextCustom"]
            )
        ],

        [
            Paragraph(
                "<b>Full Name</b>",
                styles["BodyTextCustom"]
            ),

            Paragraph(
                escape_html(full_name),
                styles["BodyTextCustom"]
            )
        ],

        [
            Paragraph(
                "<b>Default Branch</b>",
                styles["BodyTextCustom"]
            ),

            Paragraph(
                escape_html(default_branch),
                styles["BodyTextCustom"]
            )
        ],

        [
            Paragraph(
                "<b>Files Analyzed</b>",
                styles["BodyTextCustom"]
            ),

            Paragraph(
                str(len(source_files)),
                styles["BodyTextCustom"]
            )
        ]

    ]

    cover_table = Table(
        cover_data,
        colWidths=[
            45 * mm,
            125 * mm
        ]
    )

    cover_table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.HexColor("#EEF2FF")
            ),

            (
                "BACKGROUND",
                (1, 0),
                (1, -1),
                colors.HexColor("#F8FAFC")
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.6,
                colors.HexColor("#CBD5E1")
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                9
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                9
            )

        ])
    )

    story.append(
        cover_table
    )

    story.append(
        Spacer(
            1,
            20 * mm
        )
    )

    story.append(
        Paragraph(
            "Code In. Clarity Out.",
            styles["CoverSubtitle"]
        )
    )

    story.append(
        Paragraph(
            "Decode. Understand. Build.",
            styles["CoverSubtitle"]
        )
    )

    story.append(
        PageBreak()
    )

    # =================================================
    # 1. PROJECT UNDERSTANDING
    # =================================================

    story.append(
        section_title(
            "1. Project Understanding",
            styles
        )
    )

    story.append(
        create_analysis_box(
            "What This Project Does",
            project_summary,
            styles
        )
    )

    # =================================================
    # 2. TECHNOLOGY STACK
    # =================================================

    story.append(
        Spacer(1, 8)
    )

    story.append(
        section_title(
            "2. Technology Stack",
            styles
        )
    )

    story.extend(
        bullet_list(
            technology_stack,
            styles
        )
    )

    # =================================================
    # 3. ARCHITECTURE
    # =================================================

    story.append(
        Spacer(1, 8)
    )

    story.append(
        section_title(
            "3. Architecture",
            styles
        )
    )

    story.append(
        create_analysis_box(
            "System Architecture",
            architecture,
            styles
        )
    )

    # =================================================
    # 4. DEPENDENCIES
    # =================================================

    story.append(
        Spacer(1, 8)
    )

    story.append(
        section_title(
            "4. Dependencies",
            styles
        )
    )

    story.extend(
        bullet_list(
            dependencies,
            styles
        )
    )

    # =================================================
    # 5. DATABASE
    # =================================================

    story.append(
        Spacer(1, 8)
    )

    story.append(
        section_title(
            "5. Database",
            styles
        )
    )

    story.append(
        create_analysis_box(
            "Database Structure",
            database,
            styles
        )
    )

    # =================================================
    # 6. AUTHENTICATION
    # =================================================

    story.append(
        Spacer(1, 8)
    )

    story.append(
        section_title(
            "6. Authentication",
            styles
        )
    )

    story.append(
        create_analysis_box(
            "Authentication & Authorization",
            authentication,
            styles
        )
    )

    # =================================================
    # 7. API REQUESTS
    # =================================================

    story.append(
        PageBreak()
    )

    story.append(
        section_title(
            "7. Important API Requests",
            styles
        )
    )

    story.extend(
        build_api_requests(
            important_requests,
            styles
        )
    )

    # =================================================
    # 8. REBUILD OPTIONS
    # =================================================

    story.append(
        Spacer(1, 12)
    )

    story.append(
        section_title(
            "8. Three Ways to Rebuild This Project",
            styles
        )
    )

    story.extend(
        build_rebuild_options(
            rebuild_options,
            styles
        )
    )

    # =================================================
    # 9. FILE-BY-FILE ANALYSIS
    # =================================================

    story.append(
        PageBreak()
    )

    story.append(
        section_title(
            "9. File-by-File Explanation",
            styles
        )
    )

    if file_analysis:

        story.extend(
            build_file_analysis(
                file_analysis,
                styles
            )
        )

    else:

        story.append(
            Paragraph(
                "No file-by-file AI analysis was returned.",
                styles["BodyTextCustom"]
            )
        )

    # =================================================
    # 10. SELECTED SOURCE FILES SUMMARY
    # =================================================

    story.append(
        PageBreak()
    )

    story.append(
        section_title(
            "10. Selected Source Files",
            styles
        )
    )

    if source_files:

        source_rows = [[

            Paragraph(
                "File",
                styles["TableHeader"]
            ),

            Paragraph(
                "Category",
                styles["TableHeader"]
            ),

            Paragraph(
                "Size",
                styles["TableHeader"]
            )

        ]]

        for file in source_files:

            path = safe_text(
                file.get("path"),
                "Unknown"
            )

            categories = file.get(
                "categories",
                []
            )

            content = file.get(
                "content",
                ""
            )

            source_rows.append([

                Paragraph(
                    escape_html(path),
                    styles["TableCell"]
                ),

                Paragraph(
                    escape_html(
                        safe_text(
                            categories,
                            "Uncategorized"
                        )
                    ),
                    styles["TableCell"]
                ),

                Paragraph(
                    f"{len(str(content)):,} characters",
                    styles["TableCell"]
                )

            ])

        source_table = Table(
            source_rows,
            colWidths=[
                75 * mm,
                55 * mm,
                40 * mm
            ],
            repeatRows=1
        )

        source_table.setStyle(
            TableStyle([

                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#6366F1")
                ),

                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#CBD5E1")
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP"
                ),

                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, -1),
                    colors.HexColor("#F8FAFC")
                ),

                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),

                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                )

            ])
        )

        story.append(
            source_table
        )

    else:

        story.append(
            Paragraph(
                "No source files were selected.",
                styles["BodyTextCustom"]
            )
        )

    # =================================================
    # 11. COMPLETE SOURCE CODE
    # =================================================

    story.append(
        PageBreak()
    )

    story.append(
        section_title(
            "11. Complete Selected Source Code",
            styles
        )
    )

    story.append(
        Paragraph(
            "The following section contains the complete source code "
            "of every file selected for analysis.",
            styles["BodyTextCustom"]
        )
    )

    story.extend(
        build_source_code(
            source_files,
            styles
        )
    )

    # =================================================
    # FINAL
    # =================================================

    story.append(
        Spacer(
            1,
            15
        )
    )

    story.append(
        Paragraph(
            "End of Gitora AI Report",
            styles["CoverSubtitle"]
        )
    )

    # =================================================
    # BUILD PDF
    # =================================================

    print(
        "PDF SERVICE: Building PDF document..."
    )

    document.build(

        story,

        onFirstPage=add_page_number,

        onLaterPages=add_page_number

    )

    # =================================================
    # RESET BUFFER
    # =================================================

    buffer.seek(0)

    print(
        "PDF SERVICE: PDF generated successfully."
    )

    print(
        "PDF SERVICE: PDF size:",
        len(buffer.getvalue()),
        "bytes"
    )

    return buffer